image: node:latest

variables:
  PUBLIC_URL: https://cs409-final-project.gitlab.io/ # Update with your GitLab Pages URL

cache:
  paths:
    - node_modules

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install                        # Install all dependencies
    - npm run build                      # Build for production
    - mv public _public                  # Rename CRA's public folder (optional, remove if unnecessary)
    - mv build public                    # Move build files to public folder for GitLab Pages
  artifacts:
    paths:
      - public                           # Deploy the public folder as a GitLab Pages artifact
  only:
    - master                             # Run this job only on the master branch
